services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.develop
    container_name: keru-frontend
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    restart: unless-stopped
